# Generated by Django 5.1.1 on 2025-04-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(choices=[('Software Development', 'Software Development'), ('Testing', 'Testing'), ('Sales', 'Sales'), ('Customer Support', 'Customer Support'), ('Technical Support', 'Technical Support'), ('Manager', 'Manager'), ('HR', 'HR')], max_length=200, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('experience', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
            ],
        ),
    ]
