# Generated by Django 5.1.1 on 2024-09-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('mobile_no', models.IntegerField()),
                ('destination', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
