# Generated by Django 5.1.1 on 2024-09-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='destination',
            new_name='role',
        ),
    ]
