# Generated by Django 5.1.1 on 2024-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_destination_employees_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
